# Generated by Django 2.2.4 on 2019-10-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lattitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('longtitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('capacity', models.DecimalField(decimal_places=15, max_digits=20)),
            ],
        ),
    ]
